export const LOGS_MAX_BLOCK_RANGE = 10_000n;

export const MILLISECONDS_PER_DAY = 86_400_000;

export const MILLISECONDS_PER_WEEK = 604_800_000;

export const MILLISECONDS_PER_YEAR = 31_556_952_000;

export const SECONDS_PER_DAY = 86_400;

export const TEN_SECONDS_IN_MILLISECONDS = 10_000;

export const ONE_MINUTE_IN_MILLISECONDS = 60_000;

export const FIVE_MINUTES_IN_MILLISECONDS = 300_000;

export const TEN_MINUTES_IN_MILLISECONDS = 600_000;

export const FIFTY_MINUTES_IN_MILLISECONDS = 3_000_000;

export const ONE_HOUR_IN_MILLISECONDS = 3_600_000;

export const NATIVE_TOKEN_CONTRACT_ADDRESS = "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE";

export const USDC_DECIMALS = 6;

export const LP_PRESENTATION_DECIMALS = 4;

export const COINGECKO_MAX_DAYS_FOR_HOURLY_DATA = 89;

export const MAX_CONSECUTIVE_RETRY = 10;
